@api = http://localhost:3000/api

### get all users
GET {{api}}/users

### create a new user
POST {{api}}/users
Content-Type: application/json

{
  "firstname": "Kriz",
  "lastname": "Palacios",
  "email": "krp1@yopmail.com"
}

### get single user
GET {{api}}/users/9

### update single user
PUT {{api}}/users/9
Content-Type: application/json

{
  "firstname": "Kriz",
  "active": false,
  "email": "krp2@yopmail.com"
}

### delete single user
DELETE  {{api}}/users/1
